'use strict';
const APP_VERSION='1.3.0',UI_VERSION='ROSE-CA-F5-V1.3';let D=[];
const panel=document.getElementById('panel'),latest=document.getElementById('latest');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const balls=a=>a.map(n=>`<span class="ball">${String(n).padStart(2,'0')}</span>`).join('');
const freq=ds=>{let f=Array(40).fill(0);ds.forEach(r=>r.numbers.forEach(n=>f[n]++));return f};
const gaps=a=>a.slice(1).map((n,i)=>n-a[i]);
function saveUserRows(rows){localStorage.setItem('rose_ca_f5_user_rows',JSON.stringify(rows))}
function userRows(){try{return JSON.parse(localStorage.getItem('rose_ca_f5_user_rows')||'[]')}catch{return[]}}
function rebuild(base){let map=new Map([...base,...userRows()].map(r=>[r.date,r]));D=[...map.values()].sort((a,b)=>b.date.localeCompare(a.date))}
function latestView(){if(!D.length){latest.innerHTML='<b>資料庫尚無資料</b>';return}const r=D[0];latest.innerHTML=`<div class="statusTop"><div><b>📡 資料庫 ${D.length} 期</b><small>內建資料可離線使用；你新增/匯入的資料保存在此裝置。</small></div><span id="net" class="online">● 線上</span></div><div class="latestRow"><div><small>最新資料</small><strong>${esc(r.date)}　#${esc(r.draw)}</strong></div><div class="balls">${balls(r.numbers)}</div></div><div class="notice">官方驗證資料目前內建至 2026-09-11。若你有更新一期，可在「歷史資料」手動新增或匯入 CSV；不會把未驗證號碼冒充官方資料。</div>`;updateNet()}
function updateNet(){let n=document.getElementById('net');if(n){n.textContent=navigator.onLine?'● 線上':'● 離線可用';n.className=navigator.onLine?'online':'offline'}}
addEventListener('online',updateNet);addEventListener('offline',updateNet);
function history(){panel.innerHTML=`<h2>📚 歷史資料</h2><div class="toolbar"><label class="filebtn">匯入 CSV<input id="csv" type="file" accept=".csv,text/csv"></label><button class="action secondary" id="exportCsv">匯出 CSV</button><button class="action danger" id="clearImport">清除自行新增</button></div><details open><summary>➕ 手動新增一期</summary><div class="formrow"><input id="dDate" type="date"><input id="dDraw" inputmode="numeric" placeholder="期號"><input id="dNums" placeholder="例如 19 21 33 35 38"><button class="action" id="addDraw">加入資料庫</button></div><small>號碼必須是 1～39、不重複共 5 碼。手動資料只存在你的瀏覽器。</small></details><div class="tablewrap"><table><thead><tr><th>日期</th><th>期號</th><th>號碼</th></tr></thead><tbody>${D.map(r=>`<tr><td>${esc(r.date)}</td><td>#${esc(r.draw)}</td><td>${r.numbers.map(n=>String(n).padStart(2,'0')).join(' ')}</td></tr>`).join('')}</tbody></table></div>`;document.getElementById('csv').onchange=importCSV;document.getElementById('clearImport').onclick=()=>{if(confirm('清除你自行新增/匯入的資料？內建資料不會刪除。')){localStorage.removeItem('rose_ca_f5_user_rows');location.reload()}};document.getElementById('addDraw').onclick=addDraw;document.getElementById('exportCsv').onclick=exportCSV}
function addDraw(){let date=document.getElementById('dDate').value,draw=+document.getElementById('dDraw').value,nums=(document.getElementById('dNums').value.match(/\d+/g)||[]).map(Number).sort((a,b)=>a-b);if(!date||!draw||nums.length!==5||new Set(nums).size!==5||nums.some(n=>n<1||n>39))return alert('請確認日期、期號，以及 5 個不重複的 1～39 號碼');let rows=userRows().filter(r=>r.date!==date);rows.push({date,draw,numbers:nums,source:'manual'});saveUserRows(rows);location.reload()}
function numbers(){let f=freq(D),last={};D.forEach((r,i)=>r.numbers.forEach(n=>{if(last[n]===undefined)last[n]=i}));let recent=freq(D.slice(0,20));let arr=Array.from({length:39},(_,i)=>i+1).sort((a,b)=>recent[b]-recent[a]||f[b]-f[a]||a-b);panel.innerHTML=`<h2>🔢 號碼研究</h2><p>依最近20期排序；顯示全資料次數、最近20期次數、遺漏。只是歷史描述。</p><div class="numgrid">${arr.map(n=>`<div><b>${String(n).padStart(2,'0')}</b><small>全 ${f[n]}｜近20 ${recent[n]}｜遺漏 ${last[n]??D.length}</small></div>`).join('')}</div>`}
function structure(){let rows=D.map(r=>{let odd=r.numbers.filter(n=>n%2).length,sum=r.numbers.reduce((a,b)=>a+b,0),g=gaps(r.numbers),con=g.filter(x=>x===1).length,span=r.numbers[4]-r.numbers[0];return `<tr><td>${r.date}</td><td>${odd}:${5-odd}</td><td>${sum}</td><td>${span}</td><td>${con}</td><td>${g.join('-')}</td></tr>`});panel.innerHTML=`<h2>🧩 結構研究</h2><div class="tablewrap"><table><thead><tr><th>日期</th><th>奇:偶</th><th>和值</th><th>跨度</th><th>連號Gap</th><th>Gap</th></tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function combo(){let pm=new Map,tm=new Map;D.forEach(r=>{for(let i=0;i<5;i++)for(let j=i+1;j<5;j++){let k=`${r.numbers[i]}-${r.numbers[j]}`;pm.set(k,(pm.get(k)||0)+1);for(let z=j+1;z<5;z++){let t=`${r.numbers[i]}-${r.numbers[j]}-${r.numbers[z]}`;tm.set(t,(tm.get(t)||0)+1)}}});let p=[...pm].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,24),t=[...tm].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,18);panel.innerHTML=`<h2>💥 組合共現</h2><h3>Pair TOP 24</h3><div class="chips">${p.map(([k,v])=>`<span>${k}｜${v}次</span>`).join('')}</div><h3>Triple TOP 18</h3><div class="chips">${t.map(([k,v])=>`<span>${k}｜${v}次</span>`).join('')}</div>`}
function transfer(){let overlap=[0,0,0,0,0,0],trans=Array.from({length:40},()=>Array(40).fill(0));for(let i=0;i<D.length-1;i++){let newer=D[i],older=D[i+1],s=new Set(older.numbers),c=newer.numbers.filter(n=>s.has(n)).length;overlap[c]++;older.numbers.forEach(a=>newer.numbers.forEach(b=>trans[a][b]++))}let last=D[0].numbers,items=last.map(a=>{let top=Array.from({length:39},(_,i)=>i+1).filter(b=>b!==a).sort((x,y)=>trans[a][y]-trans[a][x]||x-y).slice(0,5);return `<div class="transferCard"><b>${String(a).padStart(2,'0')} 後續共現</b><div>${top.map(b=>`${String(b).padStart(2,'0')}(${trans[a][b]})`).join('　')}</div></div>`}).join('');panel.innerHTML=`<h2>🔁 拖牌／轉移研究</h2><p>相鄰期重複統計：</p><div class="chips">${overlap.map((v,i)=>`<span>重複${i}碼｜${v}次</span>`).join('')}</div><h3>以上一期號碼為條件的下一期共現</h3><div class="transferGrid">${items}</div><p class="muted">只描述歷史條件關係，不代表下一期必然發生。</p>`}
function paper(){panel.innerHTML=`<h2>📜 紙本研究模式</h2><div class="paper">${D.map((r,i)=>{let prev=D[i+1],rep=prev?r.numbers.filter(n=>prev.numbers.includes(n)):[];return `<div><span>${r.date.slice(5)}</span>${r.numbers.map(n=>`<b class="${rep.includes(n)?'repeat':''}">${String(n).padStart(2,'0')}</b>`).join('')}</div>`}).join('')}</div><p class="muted">粉色標記＝與前一期重複號碼。</p>`}
function walk(){if(D.length<12){panel.innerHTML='<h2>🧪 Walk-forward</h2><p>至少需要 12 期資料。</p>';return}let asc=[...D].reverse(),tests=[];for(let i=10;i<asc.length;i++){let train=asc.slice(0,i),f=freq(train),pick=Array.from({length:39},(_,k)=>k+1).sort((a,b)=>f[b]-f[a]||a-b).slice(0,5),hit=asc[i].numbers.filter(n=>pick.includes(n)).length;tests.push({date:asc[i].date,pick,actual:asc[i].numbers,hit})}let dist=[0,0,0,0,0,0];tests.forEach(x=>dist[x.hit]++);let avg=tests.reduce((s,x)=>s+x.hit,0)/tests.length;panel.innerHTML=`<h2>🧪 Walk-forward 嚴格盲測</h2><div class="metric"><b>${tests.length}</b><small>盲測期數</small></div><div class="metric"><b>${avg.toFixed(2)}</b><small>平均命中碼數／期</small></div><p>基準模型：每一期只使用該期以前資料，取累積頻次前5碼。這是模型回測成績，不是中獎率。</p><div class="chips">${dist.map((v,i)=>`<span>${i}碼命中｜${v}期</span>`).join('')}</div><div class="tablewrap"><table><thead><tr><th>測試日</th><th>研究組合</th><th>實際</th><th>命中</th></tr></thead><tbody>${tests.slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${x.pick.map(n=>String(n).padStart(2,'0')).join(' ')}</td><td>${x.actual.map(n=>String(n).padStart(2,'0')).join(' ')}</td><td><b>${x.hit}</b></td></tr>`).join('')}</tbody></table></div>`}
function daily(){let saved=[];try{saved=JSON.parse(localStorage.getItem('rose_ca_daily')||'[]')}catch{}panel.innerHTML=`<h2>🗂️ 每日研究存檔</h2><p>離線也能儲存於這台裝置。</p><textarea id="note" placeholder="輸入今天的研究觀察…"></textarea><button class="action" id="saveNote">儲存本機快照</button><button class="action danger" id="clearNotes">清除全部</button><div>${saved.map(x=>`<div class="note"><b>${esc(x.time)}</b><br>${esc(x.text).replace(/\n/g,'<br>')}</div>`).join('')}</div>`;document.getElementById('saveNote').onclick=()=>{let t=document.getElementById('note').value.trim();if(!t)return;saved.unshift({time:new Date().toLocaleString('zh-TW'),text:t});localStorage.setItem('rose_ca_daily',JSON.stringify(saved));daily()};document.getElementById('clearNotes').onclick=()=>{if(confirm('清除所有研究筆記？')){localStorage.removeItem('rose_ca_daily');daily()}}}
function importCSV(e){let file=e.target.files[0];if(!file)return;let rd=new FileReader;rd.onload=()=>{let lines=rd.result.trim().split(/\r?\n/),start=/date/i.test(lines[0])?1:0;let rows=lines.slice(start).map(line=>line.split(',')).filter(a=>a.length>=7).map(a=>({date:a[0].trim(),draw:+a[1],numbers:a.slice(2,7).map(Number).sort((x,y)=>x-y),source:'import'})).filter(r=>/^\d{4}-\d{2}-\d{2}$/.test(r.date)&&r.draw&&r.numbers.length===5&&new Set(r.numbers).size===5&&r.numbers.every(n=>n>=1&&n<=39));if(!rows.length)return alert('CSV 格式不符。格式：date,draw,n1,n2,n3,n4,n5');let map=new Map([...userRows(),...rows].map(r=>[r.date,r]));saveUserRows([...map.values()]);location.reload()};rd.readAsText(file)}
function exportCSV(){let text='date,draw,n1,n2,n3,n4,n5\n'+D.map(r=>[r.date,r.draw,...r.numbers].join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download=`ROSE_CA_F5_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
const views={history,paper,numbers,structure,transfer,combo,walk,daily};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{views[b.dataset.view]();panel.scrollIntoView({behavior:'smooth',block:'start'})});
(async()=>{let base;try{base=await fetch('./data/fantasy5-history.json').then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()})}catch(e){let c=await caches.match('./data/fantasy5-history.json');if(!c)throw e;base=await c.json()}rebuild(base);latestView();history()})().catch(e=>{latest.innerHTML='<b>資料載入失敗</b>';panel.innerHTML=`<h2>資料載入失敗</h2><p>${esc(e.message)}</p>`});
if('serviceWorker'in navigator)addEventListener('load',async()=>{try{let reg=await navigator.serviceWorker.register('./service-worker.js?v=1.3.0');reg.update()}catch(e){console.warn(e)}});
