'use strict';
const APP_VERSION='1.4.0', UI_VERSION='ROSE-CA-F5-V1.4'; let D=[];
const panel=document.getElementById('panel'), latest=document.getElementById('latest');
const balls=a=>a.map(n=>`<span class="ball">${String(n).padStart(2,'0')}</span>`).join('');
const freq=ds=>{let f=Array(40).fill(0);ds.forEach(r=>r.numbers.forEach(n=>f[n]++));return f};
const gaps=a=>a.slice(1).map((n,i)=>n-a[i]);
function latestView(){const r=D[0];latest.innerHTML=`<div class="latest-top"><div><div class="dbline">📡 資料庫 <b>${D.length} 期</b><span class="online">● 離線可用</span></div><small>目前內建資料更新至 California 官方已確認的最新開獎。</small></div><div class="latest-meta"><small>最新資料</small><strong>${r.date}　#${r.draw}</strong></div><div class="balls">${balls(r.numbers)}</div></div>`}
function history(){panel.innerHTML=`<h2>📚 歷史資料</h2><p>目前內建 ${D.length} 期真實官方資料樣本。可匯入 CSV 擴充；格式：date,draw,n1,n2,n3,n4,n5</p><input id="csv" type="file" accept=".csv,text/csv"><button class="action" id="clearImport">清除匯入資料</button><div class="tablewrap"><table><thead><tr><th>日期</th><th>期號</th><th>號碼</th></tr></thead><tbody>${D.map(r=>`<tr><td>${r.date}</td><td>#${r.draw}</td><td>${r.numbers.map(n=>String(n).padStart(2,'0')).join(' ')}</td></tr>`).join('')}</tbody></table></div>`;document.getElementById('csv').onchange=importCSV;document.getElementById('clearImport').onclick=()=>{localStorage.removeItem('rose_ca_f5_import');location.reload()}}
function numbers(){let f=freq(D), last={};D.forEach((r,i)=>r.numbers.forEach(n=>{if(last[n]===undefined)last[n]=i}));let arr=Array.from({length:39},(_,i)=>i+1).sort((a,b)=>f[b]-f[a]||a-b);panel.innerHTML=`<h2>🔢 號碼研究</h2><p>以下是目前資料集的出現次數與距最新一期遺漏期數，不代表未來中獎率。</p><div class="numgrid">${arr.map(n=>`<div><b>${String(n).padStart(2,'0')}</b><small>${f[n]}次｜遺漏 ${last[n]??D.length} 期</small></div>`).join('')}</div>`}
function structure(){let rows=D.map(r=>{let odd=r.numbers.filter(n=>n%2).length,sum=r.numbers.reduce((a,b)=>a+b,0),g=gaps(r.numbers),con=g.filter(x=>x===1).length;return `<tr><td>${r.date}</td><td>${odd}:${5-odd}</td><td>${sum}</td><td>${con}</td><td>${g.join('-')}</td></tr>`});panel.innerHTML=`<h2>🧩 結構研究</h2><div class="tablewrap"><table><thead><tr><th>日期</th><th>奇:偶</th><th>和值</th><th>連號</th><th>Gap</th></tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function combo(){let m=new Map;D.forEach(r=>{for(let i=0;i<5;i++)for(let j=i+1;j<5;j++){let k=`${r.numbers[i]}-${r.numbers[j]}`;m.set(k,(m.get(k)||0)+1)}});let a=[...m].sort((x,y)=>y[1]-x[1]).slice(0,30);panel.innerHTML=`<h2>💥 Pair 共現</h2><p>目前資料集共同出現次數最高的 Pair。</p><div class="chips">${a.map(([k,v])=>`<span>${k}｜${v}次</span>`).join('')}</div>`}
function transfer(){let counts=[0,0,0,0,0,0];for(let i=0;i<D.length-1;i++){let s=new Set(D[i+1].numbers),c=D[i].numbers.filter(n=>s.has(n)).length;counts[c]++}panel.innerHTML=`<h2>🔁 鄰期重複／拖牌</h2><p>比較相鄰兩期有多少號碼重複。</p><div class="chips">${counts.map((v,i)=>`<span>重複 ${i} 碼｜${v} 次</span>`).join('')}</div><p class="muted">這是歷史描述統計，不代表下一期必然延續。</p>`}
function paper(){panel.innerHTML=`<h2>📜 紙本研究模式</h2><div class="paper">${D.map(r=>`<div><span>${r.date.slice(5)}</span>${r.numbers.map(n=>`<b>${String(n).padStart(2,'0')}</b>`).join('')}</div>`).join('')}</div>`}
function walk(){if(D.length<8){panel.innerHTML='<h2>🧪 Walk-forward</h2><p>資料不足。</p>';return}let asc=[...D].reverse(),tests=[];for(let i=7;i<asc.length;i++){let train=asc.slice(0,i),f=freq(train),pick=Array.from({length:39},(_,k)=>k+1).sort((a,b)=>f[b]-f[a]||a-b).slice(0,5),hit=asc[i].numbers.filter(n=>pick.includes(n)).length;tests.push({date:asc[i].date,pick,actual:asc[i].numbers,hit})}let avg=tests.reduce((s,x)=>s+x.hit,0)/tests.length;panel.innerHTML=`<h2>🧪 Walk-forward 嚴格盲測</h2><p>示範模型：每一期只用該期以前資料，以歷史頻次前5碼產生研究組合。平均命中 <b>${avg.toFixed(2)}</b> 碼／期；這不是中獎率。</p><div class="tablewrap"><table><thead><tr><th>測試日</th><th>研究組合</th><th>實際</th><th>命中</th></tr></thead><tbody>${tests.map(x=>`<tr><td>${x.date}</td><td>${x.pick.join(' ')}</td><td>${x.actual.join(' ')}</td><td>${x.hit}</td></tr>`).join('')}</tbody></table></div>`}
function daily(){let saved=JSON.parse(localStorage.getItem('rose_ca_daily')||'[]');panel.innerHTML=`<h2>🗂️ 每日研究存檔</h2><textarea id="note" placeholder="輸入今天的研究觀察…"></textarea><button class="action" id="saveNote">儲存本機快照</button><div>${saved.map(x=>`<div class="note"><b>${x.time}</b><br>${x.text.replace(/</g,'&lt;')}</div>`).join('')}</div>`;document.getElementById('saveNote').onclick=()=>{let t=document.getElementById('note').value.trim();if(!t)return;saved.unshift({time:new Date().toLocaleString('zh-TW'),text:t});localStorage.setItem('rose_ca_daily',JSON.stringify(saved));daily()}}
function importCSV(e){let file=e.target.files[0];if(!file)return;let rd=new FileReader;rd.onload=()=>{let rows=rd.result.trim().split(/\r?\n/).slice(1).map(line=>line.split(',')).filter(a=>a.length>=7).map(a=>({date:a[0].trim(),draw:+a[1],numbers:a.slice(2,7).map(Number).sort((x,y)=>x-y)})).filter(r=>r.numbers.length===5&&r.numbers.every(n=>n>=1&&n<=39));if(!rows.length)return alert('CSV 格式不符');localStorage.setItem('rose_ca_f5_import',JSON.stringify(rows));location.reload()};rd.readAsText(file)}
const views={history,paper,numbers,structure,transfer,combo,walk,daily};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{views[b.dataset.view]();panel.scrollIntoView({behavior:'smooth'})});
(async()=>{let base=await fetch('./data/fantasy5-history.json',{cache:'no-store'}).then(r=>r.json());let imp=JSON.parse(localStorage.getItem('rose_ca_f5_import')||'[]');let map=new Map([...base,...imp].map(r=>[r.date,r]));D=[...map.values()].sort((a,b)=>b.date.localeCompare(a.date));latestView();history()})().catch(e=>panel.innerHTML=`<h2>資料載入失敗</h2><p>${e.message}</p>`);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
