'use strict';
const APP_VERSION='1.5.0', UI_VERSION='ROSE-CA-F5-V1.5'; let D=[];
const panel=document.getElementById('panel'), latest=document.getElementById('latest');
const balls=a=>a.map(n=>`<span class="ball">${String(n).padStart(2,'0')}</span>`).join('');
const freq=ds=>{let f=Array(40).fill(0);ds.forEach(r=>r.numbers.forEach(n=>f[n]++));return f};
const gaps=a=>a.slice(1).map((n,i)=>n-a[i]);
function latestView(){const r=D[0];latest.innerHTML=`<div class="latest-top"><div><div class="dbline">🎯 最新資料 <span class="status">● 離線可用</span></div><div class="latest-meta">${r.date}｜Draw #${r.draw}｜資料庫 ${D.length} 期</div></div><div class="balls">${balls(r.numbers)}</div></div>`}
function history(){panel.innerHTML=`<h2>📚 歷史資料</h2><p>目前內建 ${D.length} 期真實官方資料樣本。可匯入 CSV 擴充；格式：date,draw,n1,n2,n3,n4,n5</p><input id="csv" type="file" accept=".csv,text/csv"><button class="action" id="clearImport">清除匯入資料</button><div class="tablewrap"><table><thead><tr><th>日期</th><th>期號</th><th>號碼</th></tr></thead><tbody>${D.map(r=>`<tr><td>${r.date}</td><td>#${r.draw}</td><td>${r.numbers.map(n=>String(n).padStart(2,'0')).join(' ')}</td></tr>`).join('')}</tbody></table></div>`;document.getElementById('csv').onchange=importCSV;document.getElementById('clearImport').onclick=()=>{localStorage.removeItem('rose_ca_f5_import');location.reload()}}
function numbers(){let f=freq(D), last={};D.forEach((r,i)=>r.numbers.forEach(n=>{if(last[n]===undefined)last[n]=i}));let arr=Array.from({length:39},(_,i)=>i+1).sort((a,b)=>f[b]-f[a]||a-b);panel.innerHTML=`<h2>🔢 號碼研究</h2><p>以下是目前資料集的出現次數與距最新一期遺漏期數，不代表未來中獎率。</p><div class="numgrid">${arr.map(n=>`<div><b>${String(n).padStart(2,'0')}</b><small>${f[n]}次｜遺漏 ${last[n]??D.length} 期</small></div>`).join('')}</div>`}
function structure(){let rows=D.map(r=>{let odd=r.numbers.filter(n=>n%2).length,sum=r.numbers.reduce((a,b)=>a+b,0),g=gaps(r.numbers),con=g.filter(x=>x===1).length;return `<tr><td>${r.date}</td><td>${odd}:${5-odd}</td><td>${sum}</td><td>${con}</td><td>${g.join('-')}</td></tr>`});panel.innerHTML=`<h2>🧩 結構研究</h2><div class="tablewrap"><table><thead><tr><th>日期</th><th>奇:偶</th><th>和值</th><th>連號</th><th>Gap</th></tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function combo(){let m=new Map;D.forEach(r=>{for(let i=0;i<5;i++)for(let j=i+1;j<5;j++){let k=`${r.numbers[i]}-${r.numbers[j]}`;m.set(k,(m.get(k)||0)+1)}});let a=[...m].sort((x,y)=>y[1]-x[1]).slice(0,30);panel.innerHTML=`<h2>💥 Pair 共現</h2><p>目前資料集共同出現次數最高的 Pair。</p><div class="chips">${a.map(([k,v])=>`<span>${k}｜${v}次</span>`).join('')}</div>`}
function transfer(){let counts=[0,0,0,0,0,0];for(let i=0;i<D.length-1;i++){let s=new Set(D[i+1].numbers),c=D[i].numbers.filter(n=>s.has(n)).length;counts[c]++}panel.innerHTML=`<h2>🔁 鄰期重複／拖牌</h2><p>比較相鄰兩期有多少號碼重複。</p><div class="chips">${counts.map((v,i)=>`<span>重複 ${i} 碼｜${v} 次</span>`).join('')}</div><p class="muted">這是歷史描述統計，不代表下一期必然延續。</p>`}
function paper(){panel.innerHTML=`<h2>📜 紙本研究模式</h2><div class="paper">${D.map(r=>`<div><span>${r.date.slice(5)}</span>${r.numbers.map(n=>`<b>${String(n).padStart(2,'0')}</b>`).join('')}</div>`).join('')}</div>`}
function walk(){if(D.length<8){panel.innerHTML='<h2>🧪 Walk-forward</h2><p>資料不足。</p>';return}let asc=[...D].reverse(),tests=[];for(let i=7;i<asc.length;i++){let train=asc.slice(0,i),f=freq(train),pick=Array.from({length:39},(_,k)=>k+1).sort((a,b)=>f[b]-f[a]||a-b).slice(0,5),hit=asc[i].numbers.filter(n=>pick.includes(n)).length;tests.push({date:asc[i].date,pick,actual:asc[i].numbers,hit})}let avg=tests.reduce((s,x)=>s+x.hit,0)/tests.length;panel.innerHTML=`<h2>🧪 Walk-forward 嚴格盲測</h2><p>示範模型：每一期只用該期以前資料，以歷史頻次前5碼產生研究組合。平均命中 <b>${avg.toFixed(2)}</b> 碼／期；這不是中獎率。</p><div class="tablewrap"><table><thead><tr><th>測試日</th><th>研究組合</th><th>實際</th><th>命中</th></tr></thead><tbody>${tests.map(x=>`<tr><td>${x.date}</td><td>${x.pick.join(' ')}</td><td>${x.actual.join(' ')}</td><td>${x.hit}</td></tr>`).join('')}</tbody></table></div>`}
function daily(){let saved=JSON.parse(localStorage.getItem('rose_ca_daily')||'[]');panel.innerHTML=`<h2>🗂️ 每日研究存檔</h2><textarea id="note" placeholder="輸入今天的研究觀察…"></textarea><button class="action" id="saveNote">儲存本機快照</button><div>${saved.map(x=>`<div class="note"><b>${x.time}</b><br>${x.text.replace(/</g,'&lt;')}</div>`).join('')}</div>`;document.getElementById('saveNote').onclick=()=>{let t=document.getElementById('note').value.trim();if(!t)return;saved.unshift({time:new Date().toLocaleString('zh-TW'),text:t});localStorage.setItem('rose_ca_daily',JSON.stringify(saved));daily()}}

function stats(){let f=freq(D),last={};D.forEach((r,i)=>r.numbers.forEach(n=>{if(last[n]===undefined)last[n]=i}));let arr=Array.from({length:39},(_,i)=>i+1).sort((a,b)=>f[b]-f[a]||a-b);let r=D[0],odd=r.numbers.filter(n=>n%2).length,sum=r.numbers.reduce((a,b)=>a+b,0),g=gaps(r.numbers);panel.innerHTML=`<h2>📊 統計分析</h2><p>把原本「號碼研究＋結構研究」合併成一頁。最新一期：奇偶 ${odd}:${5-odd}｜和值 ${sum}｜Gap ${g.join('-')}。</p><div class="numgrid">${arr.map(n=>`<div><b>${String(n).padStart(2,'0')}</b><small>${f[n]}次｜遺漏 ${last[n]??D.length}期</small></div>`).join('')}</div><p class="muted">統計分數只描述歷史資料，不是中獎機率。</p>`}
function daily(){let f=freq(D),recent=freq(D.slice(0,12)),miss={};D.forEach((r,i)=>r.numbers.forEach(n=>{if(miss[n]===undefined)miss[n]=i}));panel.innerHTML=`<h2>🎯 今日嚴選五組</h2><p>跟研究流程一樣先輸入規則，再產生五組。每組固定 5 碼、1～39、不重複；分數不是中獎機率。</p><div class="rulegrid"><label>必選號（空白或逗號）<input id="must" placeholder="例如 03 18"></label><label>排除號<input id="ban" placeholder="例如 01 39"></label><label>每組奇數數量<select id="odd"><option value="any">不限</option><option value="2">2 奇 3 偶</option><option value="3" selected>3 奇 2 偶</option></select></label><label>鄰期重複最多<select id="repeat"><option>1</option><option selected>2</option><option>3</option><option>5</option></select></label><label>和值下限<input id="sumMin" type="number" value="65"></label><label>和值上限<input id="sumMax" type="number" value="135"></label></div><button class="action" id="gen5">產生今日嚴選五組</button><div id="picks"></div><p class="muted">排序依：全期頻次、近12期熱度、遺漏平衡、組間分散；Walk-forward 規範不使用未來資料。</p>`;document.getElementById('gen5').onclick=generateFive;generateFive()}
function parseNums(id){return [...new Set(document.getElementById(id).value.split(/[ ,，、]+/).map(Number).filter(n=>n>=1&&n<=39))]}
function generateFive(){let must=parseNums('must'),ban=new Set(parseNums('ban')),oddRule=document.getElementById('odd').value,repMax=+document.getElementById('repeat').value,min=+document.getElementById('sumMin').value,max=+document.getElementById('sumMax').value;if(must.some(n=>ban.has(n))||must.length>5){document.getElementById('picks').innerHTML='<p>必選／排除規則衝突，請調整。</p>';return}let F=freq(D),R=freq(D.slice(0,12)),last={};D.forEach((r,i)=>r.numbers.forEach(n=>{if(last[n]===undefined)last[n]=i}));let prev=new Set(D[0].numbers),used=Array(40).fill(0),out=[];for(let g=0;g<5;g++){let ranked=Array.from({length:39},(_,i)=>i+1).filter(n=>!ban.has(n)).sort((a,b)=>{let sa=F[a]*1.0+R[a]*1.8+Math.min(last[a]??D.length,12)*.22-used[a]*3.2+((a*7+g*11)%13)*.01;let sb=F[b]*1.0+R[b]*1.8+Math.min(last[b]??D.length,12)*.22-used[b]*3.2+((b*7+g*11)%13)*.01;return sb-sa||a-b});let candidates=[...must];for(let n of ranked){if(candidates.includes(n))continue;let t=[...candidates,n];if(t.filter(x=>prev.has(x)).length>repMax)continue;if(oddRule!=='any'&&t.length===5&&t.filter(x=>x%2).length!==+oddRule)continue;if(t.length===5){let sum=t.reduce((a,b)=>a+b,0);if(sum<min||sum>max)continue}candidates.push(n);if(candidates.length===5)break}if(candidates.length<5){for(let n of ranked){if(!candidates.includes(n)){candidates.push(n);if(candidates.length===5)break}}}candidates.sort((a,b)=>a-b);candidates.forEach(n=>used[n]++);out.push(candidates)}document.getElementById('picks').innerHTML=out.map((p,i)=>`<div class="pick-card"><strong>第 ${i+1} 組</strong><div class="balls">${balls(p)}</div></div>`).join('')}
function importCSV(e){let file=e.target.files[0];if(!file)return;let rd=new FileReader;rd.onload=()=>{let rows=rd.result.trim().split(/\r?\n/).slice(1).map(line=>line.split(',')).filter(a=>a.length>=7).map(a=>({date:a[0].trim(),draw:+a[1],numbers:a.slice(2,7).map(Number).sort((x,y)=>x-y)})).filter(r=>r.numbers.length===5&&r.numbers.every(n=>n>=1&&n<=39));if(!rows.length)return alert('CSV 格式不符');localStorage.setItem('rose_ca_f5_import',JSON.stringify(rows));location.reload()};rd.readAsText(file)}
const views={history,stats,transfer,combo,walk,daily};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{views[b.dataset.view]();panel.scrollIntoView({behavior:'smooth'})});
(async()=>{let base=await fetch('./data/fantasy5-history.json',{cache:'no-store'}).then(r=>r.json());let imp=JSON.parse(localStorage.getItem('rose_ca_f5_import')||'[]');let map=new Map([...base,...imp].map(r=>[r.date,r]));D=[...map.values()].sort((a,b)=>b.date.localeCompare(a.date));latestView();history()})().catch(e=>panel.innerHTML=`<h2>資料載入失敗</h2><p>${e.message}</p>`);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
